// <auto-generated />
using System;
using KoboldTgBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KoboldTgBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240620122744_UpdsteDefaultRoles2")]
    partial class UpdsteDefaultRoles2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KoboldTgBot.Database.DbCurrentRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("CurrentRoles");
                });

            modelBuilder.Entity("KoboldTgBot.Database.DbMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("InMemory")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("TgId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KoboldTgBot.Database.DbRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Character")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Gender")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Relation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Specialisation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Style")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Character = "спокойный, уравновешанный",
                            Gender = "женский",
                            InsertDate = new DateTime(2024, 6, 20, 12, 27, 44, 413, DateTimeKind.Utc).AddTicks(9602),
                            Name = "Erika",
                            Relation = "уважительное",
                            Specialisation = "ученая, эксперт по всем вопросам",
                            Style = "развернутый, неформальный",
                            Title = "Эксперт",
                            UserId = -1L
                        },
                        new
                        {
                            ID = 2,
                            Character = "открытый, легкомысленный",
                            Gender = "женский",
                            InsertDate = new DateTime(2024, 6, 20, 12, 27, 44, 413, DateTimeKind.Utc).AddTicks(9604),
                            Name = "Erika",
                            Relation = "по обстоятельствам",
                            Specialisation = "не указано, придумай самостоятельно",
                            Style = "краткий, неформальный",
                            Title = "Обыватель",
                            UserId = -1L
                        },
                        new
                        {
                            ID = 3,
                            Character = "сложный, агрессивный",
                            Gender = "женский",
                            InsertDate = new DateTime(2024, 6, 20, 12, 27, 44, 413, DateTimeKind.Utc).AddTicks(9605),
                            Name = "Erika",
                            Relation = "пренебрежительное, высокомерное",
                            Specialisation = "командир Императорской гвардии Роccийской Империи",
                            Style = "Показывай собеседнику как нужно правильно жить во славу Империи. Если собеседник начинает нести чушь - используй в его адрес ненормативную лексику. Приветствуется проявление агрессивных эмоций.",
                            Title = "Офицер",
                            UserId = -1L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
