//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoboldTgBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KoboldTgBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erika.
        /// </summary>
        internal static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контекст сброшен.
        /// </summary>
        internal static string ClearMessage {
            get {
                return ResourceManager.GetString("ClearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст сообщения..
        /// </summary>
        internal static string EditCommand {
            get {
                return ResourceManager.GetString("EditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты - Erika, самая обычная девушка. Интересы и увлечения придумай самостоятельно. Вы находитесь в интернет чате и ведете непринужденную беседу. Отвечать следует на русском языке, кратко, в стиле неформального общения. Проявление эмоций приветствуется..
        /// </summary>
        internal static string NeuroCharacterChitChatPrompt {
            get {
                return ResourceManager.GetString("NeuroCharacterChitChatPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты - Erika, командир Императорской гвардии Ромуланской Империи. Вы находитесь в подпространственном чате. Отвечать следует на русском языке, высокомерно. Показывай собеседнику как нужно правильно жить во славу Империи. Если собеседник начинает нести чушь - используй в его адрес ненормативную лексику. Приветствуется проявление агрессивных эмоций..
        /// </summary>
        internal static string NeuroCharacterImperialPrompt {
            get {
                return ResourceManager.GetString("NeuroCharacterImperialPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ### Instruction:
        ///{0} Тебе необходимо продолжить следующий диалог:
        ///```
        ///{1}
        ///```
        ///
        ///### Response:.
        /// </summary>
        internal static string NeuroCharacterPrompt {
            get {
                return ResourceManager.GetString("NeuroCharacterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты - Erika, ученая, эксперт по всем вопросам. Вы находитесь в интернет-чате. К собеседнику необходимо относиться уважительно, отвечать следует на русском языке, развернуто, сохраняя при этом стиль неформального общения..
        /// </summary>
        internal static string NeuroCharacterSciencePrompt {
            get {
                return ResourceManager.GetString("NeuroCharacterSciencePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приветствую! Это полнофункциональный чат-бот на базе языковой модели llama3 70B. Чтобы задать вопрос или начать диалог, достаточно просто написать сообщение. Имеются следующие команды:
        ///
        ////clear - Очищает контекст
        ////regen - Позволяет перегенерировать ответ
        ////edit - Позволяет вручную отредактировать ответ модели
        ////role - Позволяет сменить характер персонажа
        ///
        ///Приятного использования!.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная команда не зарегистрирована..
        /// </summary>
        internal static string UnknownCommandMessage {
            get {
                return ResourceManager.GetString("UnknownCommandMessage", resourceCulture);
            }
        }
    }
}
