//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoboldTgBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KoboldTgBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вот твоя анкета:
        ///```
        ///Имя:  {0}
        ///Пол:  {1}
        ///Характер:  {2}
        ///Увлечения, интересы, специализация:  {3}
        ///```
        ///
        ///Требования к ведению переписки:
        ///```
        ///Отношение к собеседнику:  {4}
        ///Стиль общения:  {5}
        ///```
        ///
        ///Отвечать всегда следует на русском языке, это главное правило! Свое имя в ответе упоминать не нужно. Тебе необходимо продолжить следующий диалог:
        ///```
        ///@_dialog_@
        ///```.
        /// </summary>
        internal static string NeuroCharacterPrompt {
            get {
                return ResourceManager.GetString("NeuroCharacterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:  {0}
        ///
        ///Пол:  {1}
        ///
        ///Характер:  {2}
        ///
        ///Увлечения, интересы, специализация:  {3}
        ///
        ///Отношение к собеседнику:  {4}
        ///
        ///Стиль общения:  {5}.
        /// </summary>
        internal static string RoleViewInfo {
            get {
                return ResourceManager.GetString("RoleViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приветствую! Это полнофункциональный чат-бот на базе языковой модели llama3 70B. Чтобы задать вопрос или начать диалог, достаточно просто написать сообщение. Имеются следующие команды:
        ///
        ////clear - Очистка контекста. Удаляет из памяти модели всю историю вашей переписки.
        ///
        ////regen - Повторная генерация. Модель попробует составить свой ответ по-другому.
        ///
        ////edit - Редактирование ответа. Позволяет вручную исправить ответ модели для управления контекстом.
        ///
        ////mult - Отправка нескольких сообщений. После ввода ком [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
    }
}
